<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-09T18:07:47 IST" name="Default suite" finished-at="2022-12-09T18:07:50 IST" duration-ms="2805">
    <groups>
    </groups>
    <test started-at="2022-12-09T18:07:47 IST" name="Default test" finished-at="2022-12-09T18:07:50 IST" duration-ms="2805">
      <class name="TestCase.Automate_Getcommand">
        <test-method is-config="true" signature="setSpecification()[pri:0, instance:TestCase.Automate_Getcommand@55634720]" started-at="2022-12-09T18:07:47 IST" name="setSpecification" finished-at="2022-12-09T18:07:48 IST" duration-ms="860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setSpecification -->
        <test-method signature="Valid_getBanner_URL()[pri:1, instance:TestCase.Automate_Getcommand@55634720]" started-at="2022-12-09T18:07:48 IST" name="Valid_getBanner_URL" finished-at="2022-12-09T18:07:49 IST" duration-ms="1401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Valid_getBanner_URL -->
        <test-method signature="Invalid_getBanner_URL()[pri:2, instance:TestCase.Automate_Getcommand@55634720]" started-at="2022-12-09T18:07:49 IST" name="Invalid_getBanner_URL" finished-at="2022-12-09T18:07:50 IST" duration-ms="504" status="FAIL">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["payload"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["payload"] not found.
at org.json.JSONObject.get(JSONObject.java:587)
at org.json.JSONObject.getJSONArray(JSONObject.java:780)
at TestCase.Automate_Getcommand.Invalid_getBanner_URL(Automate_Getcommand.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid_getBanner_URL -->
      </class> <!-- TestCase.Automate_Getcommand -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
